// AUTO-GENERATED from art/renders/limes_roster_*.png — do not edit by hand.
// Maps "<tribe>_<arch>" -> image path (arch: spear|sword|cav|archer|siege|hero).
export const TRIBES = ["egyptian","gaul","hun","persian","roman","spartan","teuton","viking"] as const;
export type Tribe = typeof TRIBES[number];
export const ROSTER: Record<string, string> = {
  "egyptian_archer": "../art/renders/limes_roster_28_egyptian_archer_00001_.png",
  "egyptian_cav": "../art/renders/limes_roster_27_egyptian_cavalry_00001_.png",
  "egyptian_hero": "../art/renders/limes_roster_30_egyptian_hero_high_priest_sebek_00001_.png",
  "egyptian_siege": "../art/renders/limes_roster_29_egyptian_siege_00001_.png",
  "egyptian_spear": "../art/renders/limes_roster_25_egyptian_spearman_00001_.png",
  "egyptian_sword": "../art/renders/limes_roster_26_egyptian_swordsman_00001_.png",
  "gaul_archer": "../art/renders/limes_roster_10_gaul_archer_00001_.png",
  "gaul_cav": "../art/renders/limes_roster_09_gaul_cavalry_00001_.png",
  "gaul_hero": "../art/renders/limes_roster_12_gaul_hero_druidess_eponia_00001_.png",
  "gaul_siege": "../art/renders/limes_roster_11_gaul_siege_00001_.png",
  "gaul_spear": "../art/renders/limes_roster_07_gaul_spearman_00001_.png",
  "gaul_sword": "../art/renders/limes_roster_08_gaul_swordsman_00001_.png",
  "hun_archer": "../art/renders/limes_roster_22_hun_archer_00001_.png",
  "hun_cav": "../art/renders/limes_roster_21_hun_cavalry_00001_.png",
  "hun_hero": "../art/renders/limes_roster_24_hun_hero_khan_bayan_00001_.png",
  "hun_siege": "../art/renders/limes_roster_23_hun_siege_00001_.png",
  "hun_spear": "../art/renders/limes_roster_19_hun_spearman_00001_.png",
  "hun_sword": "../art/renders/limes_roster_20_hun_swordsman_00001_.png",
  "persian_archer": "../art/renders/limes_roster_46_persian_archer_00001_.png",
  "persian_cav": "../art/renders/limes_roster_45_persian_cavalry_00001_.png",
  "persian_hero": "../art/renders/limes_roster_48_persian_hero_satrap_darius_00001_.png",
  "persian_siege": "../art/renders/limes_roster_47_persian_siege_00001_.png",
  "persian_spear": "../art/renders/limes_roster_43_persian_spearman_00001_.png",
  "persian_sword": "../art/renders/limes_roster_44_persian_swordsman_00001_.png",
  "roman_archer": "../art/renders/limes_roster_04_roman_archer_00001_.png",
  "roman_cav": "../art/renders/limes_roster_03_roman_cavalry_00001_.png",
  "roman_hero": "../art/renders/limes_roster_06_roman_hero_legatus_marcus_00001_.png",
  "roman_siege": "../art/renders/limes_roster_05_roman_siege_00001_.png",
  "roman_spear": "../art/renders/limes_roster_01_roman_spearman_00001_.png",
  "roman_sword": "../art/renders/limes_roster_02_roman_swordsman_00001_.png",
  "spartan_archer": "../art/renders/limes_roster_40_spartan_archer_00001_.png",
  "spartan_cav": "../art/renders/limes_roster_39_spartan_cavalry_00001_.png",
  "spartan_hero": "../art/renders/limes_roster_42_spartan_hero_king_leonis_00001_.png",
  "spartan_siege": "../art/renders/limes_roster_41_spartan_siege_00001_.png",
  "spartan_spear": "../art/renders/limes_roster_37_spartan_spearman_00001_.png",
  "spartan_sword": "../art/renders/limes_roster_38_spartan_swordsman_00001_.png",
  "teuton_archer": "../art/renders/limes_roster_16_teuton_archer_00001_.png",
  "teuton_cav": "../art/renders/limes_roster_15_teuton_cavalry_00001_.png",
  "teuton_hero": "../art/renders/limes_roster_18_teuton_hero_warlord_drengr_00001_.png",
  "teuton_siege": "../art/renders/limes_roster_17_teuton_siege_00001_.png",
  "teuton_spear": "../art/renders/limes_roster_13_teuton_spearman_00001_.png",
  "teuton_sword": "../art/renders/limes_roster_14_teuton_swordsman_00001_.png",
  "viking_archer": "../art/renders/limes_roster_34_viking_archer_00001_.png",
  "viking_cav": "../art/renders/limes_roster_33_viking_cavalry_00001_.png",
  "viking_hero": "../art/renders/limes_roster_36_viking_hero_jarl_sigrid_00001_.png",
  "viking_siege": "../art/renders/limes_roster_35_viking_siege_00001_.png",
  "viking_spear": "../art/renders/limes_roster_31_viking_spearman_00001_.png",
  "viking_sword": "../art/renders/limes_roster_32_viking_swordsman_00001_.png",
};
